env:
  global:
    - CC_TEST_REPORTER_ID=acdec03fe2f3a1babf23bbeb39e49678c28d9f81ff0928a52f3ec25f2ae0c719
language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
  - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  skip_cleanup: true
  provider: npm
  email: stanchino@gmail.com
  api_key:
    secure: Q5HyCU8pa7b95ODvVner2Z1CweT+2yqKvHvHK2gwUCwQVPmzJUeANmiNBBDEncxFtzY1Ozia89ycVzoWjSHoe0BBej1j2Xpnd6Xnk+mibKyiUyjxpGRzW3+D/UOMgkid46ayvM5r28KQZELkOGkEBhKElA76cmpe22+a3S8BUGe1N5OJBh2U+FpJuXaUBdbS3Y7tvRHuC1Oo5uF8/gv/n0BsjaQlHAWrqKkmiUMcUXD4JEA7cLj2wMGG3noJNxPVUjrsRv07kUWd5pruRSqdYy1PDdztFzdOlocIHo7dGM4eYBuMJAGacsHEZsqUwNwt04BzT63YdgjECQBizhCYpe5LbFzdiIlMgYBGkhd8sTtg5zcgrtYJ70qk9c8GYdaScvZaxxRS+wWk1Xv3cDmt3paxNf94wJE09N3f0XFKjyY1ajoZwLhrHburssP+fb0zWLcGMGw5PxetEos9G1fuLlrk1WTYWnytjTslRQkUQzb+VptrwBB5Pe9jHCdU691ZyG9kx6RmkXOMuzOTCEcWIDTdGMxpFnRfv8tq3vgfjr2fuXaMoKP001QRxRNchd1LCJCkEOSZGsd1kpp7fWKtLnF2A6/WGnJIxdHwvXc2dcgmf6kpvwe4FrMLEjYAnnL8g6whtni2Bjzs5Tf1Fv8Vp21GSQdBe9Kp/dkqKCwuXbA=
  on:
    branch: master
    repo: stanchino/react-serverless-auth
